### ISSUE TITLE
Nothing shows in the dropdown

### ISSUE THREAD

**Issue by Tushant** [quakig/django-haystack-elasticsearch#1]
I tried your code but when I search for the product nothing is shown in the dropdown. I know the selction-ajax div is not filled with the result but in console, I see nothing. How do I show the product when typing the product name?

**Comment by wilkinj33** [comment]
Check your Developer Console in a browser, this may be an Allow Origins issue?
Edit: You may need to edit the elasticsearch.yml file and configure https://github.com/ottoyiu/django-cors-headers

**Comment by bhaskar-c** [comment]
closing the issue - as this was a case of version mismatch.  You can debug issues by running the 
Elasticsearch server and visiting http://127.0.0.1:9200/.
